<a href="https://colab.research.google.com/github/NidhiSingh25901/Numpy-For-AI-ML/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

# -----------------------------
# 1. Creating Arrays
# -----------------------------
arr1 = np.array([1, 2, 3])
arr2 = np.array([[1, 2], [3, 4]])
zeros = np.zeros((3, 3))
ones = np.ones((2, 4))
full = np.full((2, 3), 7)
identity = np.eye(3)
arange_arr = np.arange(0, 10, 2)
linspace_arr = np.linspace(0, 1, 5)
rand_arr = np.random.rand(3, 3)
randn_arr = np.random.randn(3, 3)
randint_arr = np.random.randint(0, 10, (3, 3))

# -----------------------------
# 2. Inspecting Arrays
# -----------------------------
print("Shape:", arr2.shape)
print("Dimensions:", arr2.ndim)
print("Size:", arr2.size)
print("Data type:", arr2.dtype)
print("Transpose:\n", arr2.T)

# -----------------------------
# 3. Array Operations
# -----------------------------
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)
print("Power:", a ** 2)
print("Dot Product:", np.dot(a, b))
print("Sum:", np.sum(a))
print("Mean:", np.mean(a))
print("Median:", np.median(a))
print("Std Dev:", np.std(a))
print("Min:", np.min(a))
print("Max:", np.max(a))
print("Argmin:", np.argmin(a))
print("Argmax:", np.argmax(a))
print("Round:", np.round(np.array([1.123, 2.456]), 2))

# -----------------------------
# 4. Indexing & Slicing
# -----------------------------
arr = np.arange(10)
print("First element:", arr[0])
print("Slice 1:4:", arr[1:4])
matrix = np.arange(9).reshape(3,3)
print("All rows, col 1:", matrix[:,1])
print("Row 1, all cols:", matrix[1,:])
print("Elements > 5:", matrix[matrix > 5])

# -----------------------------
# 5. Reshaping Arrays
# -----------------------------
reshaped = arr.reshape(2,5)
flattened = matrix.flatten()
raveled = matrix.ravel()
expanded = np.expand_dims(arr, axis=0)
print("Reshaped:\n", reshaped)
print("Flattened:", flattened)
print("Expanded:", expanded)

# -----------------------------
# 6. Stacking & Splitting
# -----------------------------
a = np.array([1,2,3])
b = np.array([4,5,6])
vstacked = np.vstack([a,b])
hstacked = np.hstack([a,b])
concatenated = np.concatenate([a,b], axis=0)
splitted = np.split(a,3)
print("Vstack:\n", vstacked)
print("Hstack:", hstacked)
print("Concatenated:", concatenated)
print("Splitted:", splitted)

# -----------------------------
# 7. Randomness / Sampling
# -----------------------------
np.random.seed(42)
shuffled = np.random.permutation(a)
sampled = np.random.choice(a, size=5, replace=True)
print("Shuffled:", shuffled)
print("Sampled:", sampled)


Shape: (2, 2)
Dimensions: 2
Size: 4
Data type: int64
Transpose:
 [[1 3]
 [2 4]]
Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]
Power: [1 4 9]
Dot Product: 32
Sum: 6
Mean: 2.0
Median: 2.0
Std Dev: 0.816496580927726
Min: 1
Max: 3
Argmin: 0
Argmax: 2
Round: [1.12 2.46]
First element: 0
Slice 1:4: [1 2 3]
All rows, col 1: [1 4 7]
Row 1, all cols: [3 4 5]
Elements > 5: [6 7 8]
Reshaped:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
Flattened: [0 1 2 3 4 5 6 7 8]
Expanded: [[0 1 2 3 4 5 6 7 8 9]]
Vstack:
 [[1 2 3]
 [4 5 6]]
Hstack: [1 2 3 4 5 6]
Concatenated: [1 2 3 4 5 6]
Splitted: [array([1]), array([2]), array([3])]
Shuffled: [1 2 3]
Sampled: [1 3 3 1 1]


In [3]:
mat = np.array([[1,2],[3,4]])
inv = np.linalg.inv(mat)
det = np.linalg.det(mat)
eig_vals, eig_vecs = np.linalg.eig(mat)
norm = np.linalg.norm(a)
print("Inverse:\n", inv)
print("Determinant:", det)
print("Eigenvalues:", eig_vals)
print("Norm:", norm)

# -----------------------------
# 9. Broadcasting
# -----------------------------
bcast_add = a + 5
bcast_mult = a * np.array([1,2,3])
print("Broadcast Add:", bcast_add)
print("Broadcast Multiply:", bcast_mult)

# -----------------------------
# 10. Logical / Comparison
# -----------------------------
indices = np.where(a > 2)
any_gt2 = np.any(a > 2)
all_gt0 = np.all(a > 0)
print("Indices where >2:", indices)
print("Any >2:", any_gt2)
print("All >0:", all_gt0)

# -----------------------------
# 11. Advanced Functions
# -----------------------------
log_arr = np.log(a + 1)  # add 1 to avoid log(0)
exp_arr = np.exp(a)
sqrt_arr = np.sqrt(a)
sin_arr = np.sin(a)
cos_arr = np.cos(a)
clipped_arr = np.clip(a, 1, 2)
print("Log:", log_arr)
print("Exp:", exp_arr)
print("Sqrt:", sqrt_arr)
print("Sin:", sin_arr)
print("Cos:", cos_arr)
print("Clipped:", clipped_arr)

print("\nAll NumPy commands executed successfully!")

Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Determinant: -2.0000000000000004
Eigenvalues: [-0.37228132  5.37228132]
Norm: 3.7416573867739413
Broadcast Add: [6 7 8]
Broadcast Multiply: [1 4 9]
Indices where >2: (array([2]),)
Any >2: True
All >0: True
Log: [0.69314718 1.09861229 1.38629436]
Exp: [ 2.71828183  7.3890561  20.08553692]
Sqrt: [1.         1.41421356 1.73205081]
Sin: [0.84147098 0.90929743 0.14112001]
Cos: [ 0.54030231 -0.41614684 -0.9899925 ]
Clipped: [1 2 2]

All NumPy commands executed successfully!
